- name: Install Mongodb Component
  hosts: mongodb
  become: yes
  tasks:
  - name: Copy mongo.repo to yum.repos.d
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo
  - name: install mongodb-org
    ansible.builtin.yum:
      name: mongodb-org
      state: present
  - name: start and enable the service
    ansible.builtin.yum:
      name: mongod
      state: started
      enabled: yes
  - name: enable remote connection to mongodb
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'
  - name: restart mongodb
    ansible.builtin.service:
      name: mongod
      state: restarted