- name: Install rabbitmq component
  hosts: rabbitmq
  become: yes
  tasks:
  - name: configure rabbitmq yum repos
    ansible.builtin.shell: "{{item}}"
    loop:
    - "curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash"
    - "curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash"

  - name: Install RabbitMQ
    ansible.builtin.yum:
      name: rabbitmq-server
      state: present

  - name: start rabbitmq
    ansible.builtin.service:
      name: rabbitmq-server
      state: start
      enabled: true

  - name: create rabbitmq user
    ansible.builtin.command: rabbitmqctl add_user roboshop roboshop123

  - name: setup permissions
    ansible.builtin.command: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"