- name: Install Redis components
  hosts: redis
  become: yes
  tasks:
  - name: Install redis repo
    ansible.builtin.yum:
      name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y
      state: installed
      disable_gpg_check: true